/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'aperdomob' at '24/09/16 9:09' with Gradle 2.13
 *
 * @author aperdomob, @date 24/09/16 9:09
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
